# Generated by Django 2.1.1 on 2018-10-04 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField(default=datetime.date.today)),
                ('income_description', models.CharField(max_length=256)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_date', models.DateField(default=datetime.date.today)),
                ('outcome_description', models.CharField(max_length=256)),
                ('outcome', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement_date', models.DateField(default=datetime.date.today)),
                ('reimbursement_source', models.CharField(max_length=256)),
                ('reimbursement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outcome_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Outcome')),
            ],
        ),
    ]
